require('@alipay/appx-compiler/lib/sjsEnvInit');
require('./config$');

require('../../components/conference/card/index');
require('../../components/conference/card-detail-word/index');
require('../../components/conference/operation-detail-page/operation-detail-page');
require('../../page/index/index');
require('../../page/statisticalReport/statisticalReport/statisticalReport');
require('../../page/templates/labelTemplate/labelTemplate');
require('../../page/templates/collapse/collapse');
require('../../page/organization/myOrganization/myOrganization');
require('../../page/organization/singleMember/singleMember');
require('../../page/conference/add/add');
require('../../page/conference/note/note');
require('../../page/conference/summary/summary');
require('../../page/conference/detail/detail');
require('../../page/conference/meetingRoom/meetingRoom');
require('../../page/conference/photo/photo');
require('../../page/conference/takeOff/takeOff');
